<?php
require_once '../config/config.php';
require_once '../includes/header.php';
require_once '../includes/auth.php';
require_once '../includes/functions.php';

// Ensure only patients can access
requireRole('Patient');

$patient_id = $_SESSION['patient_id'];

// Check if patient has any vitals
$has_vitals = false;
$vitals_check = $conn->prepare("SELECT COUNT(*) as vital_count FROM HealthData WHERE Patient_ID = ?");
$vitals_check->bind_param("i", $patient_id);
$vitals_check->execute();
$vital_result = $vitals_check->get_result()->fetch_assoc();
$has_vitals = ($vital_result['vital_count'] > 0);

// Get all reports for this patient
$reports = [];
$stmt = $conn->prepare("SELECT r.*, u.Full_Name as doctor_name, 
                       (SELECT u2.Full_Name FROM User u2 
                        JOIN Patient p2 ON p2.User_ID = u2.User_ID 
                        WHERE p2.Patient_ID = r.Patient_ID) as patient_name 
                       FROM Reports r
                       LEFT JOIN Doctor d ON r.Doctor_ID = d.Doctor_ID
                       LEFT JOIN User u ON d.User_ID = u.User_ID
                       WHERE r.Patient_ID = ?
                       ORDER BY r.Generated_On DESC");
$stmt->bind_param("i", $patient_id);
$stmt->execute();
$reports = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
?>

<div class="patient-reports">
    <h2>Medical Reports</h2>
    <div class="back-link">
        <a href="dashboard.php" class="btn-back"><i class="fas fa-arrow-left"></i> Back to Dashboard</a>
    </div>
    
    <div class="reports-list">
    <?php if (!empty($reports)): ?>
        <table>
            <thead>
                <tr>
                    <th>Report Date</th>
                    <th>Type</th>
                    <th>Period</th>
                    <th>Generated By</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($reports as $report): ?>
                    <tr>
                        <td><?= date('m/d/Y', strtotime($report['Generated_On'])) ?></td>
                        <td><?= htmlspecialchars($report['Report_Type']) ?></td>
                        <td><?= htmlspecialchars($report['Report_Period']) ?></td>
                        <td><?= $report['doctor_name'] ?? $report['patient_name'] ?></td>
                        <td>
                            <?php if ($report['File_Path']): ?>
                                <a href="<?= htmlspecialchars($report['File_Path']) ?>" class="btn" download>Download</a>
                            <?php else: ?>
                                <span>No file available</span>
                            <?php endif; ?>
                            <form method="POST" action="../api/delete_report.php" style="display: inline;">
                                <input type="hidden" name="report_id" value="<?= $report['Report_ID'] ?>">
                                <input type="hidden" name="action" value="delete">
                                <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this report?')">Delete</button>
                            </form>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
    <?php endif; ?>
</div>
    
    <div class="report-request">
        <h3>Request New Report</h3>
        <form action="../api/generate_report.php" method="post">
            <input type="hidden" name="patient_id" value="<?= $patient_id ?>">
            
            <div class="form-group">
                <label for="time_period">Time Period:</label>
                <select id="time_period" name="time_period" required>
                    <option value="">Select a time period</option>
                    <option value="7days">Last 7 Days</option>
                    <option value="30days">Last 30 Days</option>
                    <option value="90days">Last 90 Days</option>
                    <option value="year">Last Year</option>
                    <option value="all">All Time</option>
                </select>
            </div>
            
            <button type="submit" class="btn">Request Report</button>
        </form>
    </div>
</div>

<!-- Modal for no vitals -->
<?php if (!$has_vitals): ?>
<div id="noVitalsModal" class="modal">
    <div class="modal-content">
        <h3>No Vitals Recorded</h3>
        <p>You have not entered any vital data yet. Reports cannot be generated without vital information. Please record your vitals first.</p>
        <div class="modal-buttons">
            <a href="vitals.php" class="btn btn-primary"><i class="fas fa-heartbeat"></i> Enter Vitals</a>
            <a href="dashboard.php" class="btn btn-secondary"><i class="fas fa-arrow-left"></i> Back to Dashboard</a>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const modal = document.getElementById('noVitalsModal');

    // Show the modal if it exists
    if (modal) {
        modal.style.display = 'block';
    }

    // Close the modal when the close button is clicked

    // Close the modal when clicking outside of it
    window.addEventListener('click', function(event) {
        if (event.target === modal) {
            modal.style.display = 'none';
        }
    });
});
</script>
<?php endif; ?>

<style>
/* Modal Styles */
.modal {
    display: none;
    position: fixed;
    z-index: 1000;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.5);
    overflow: auto;
}

.modal-content {
    background-color: #fff;
    margin: 15% auto;
    padding: 2rem;
    border-radius: 12px;
    box-shadow: 0 10px 30px rgba(0, 0, 0, 0.2);
    width: 90%;
    max-width: 500px;
    text-align: center;
}

.modal-content h3 {
    color: var(--primary-dark);
    font-size: 1.5rem;
    margin-bottom: 1rem;
}

.modal-content p {
    color: var(--dark-gray);
    font-size: 1rem;
    line-height: 1.5;
    margin-bottom: 1.5rem;
}

.modal-buttons {
    display: flex;
    justify-content: center;
    gap: 1rem;
}

.btn-primary {
    background-color: var(--primary-dark);
    color: white;
    padding: 0.75rem 1.5rem;
    border-radius: 8px;
    text-decoration: none;
    transition: all 0.3s ease;
}

.btn-primary:hover {
    background-color: var(--primary);
    transform: translateY(-2px);
}

.btn-secondary {
    background-color: #6c757d;
    color: white;
    padding: 0.75rem 1.5rem;
    border: none;
    border-radius: 8px;
    cursor: pointer;
    transition: all 0.3s ease;
}

.btn-secondary:hover {
    background-color: #5a6268;
    transform: translateY(-2px);
}
</style>

<?php require_once '../includes/footer.php'; ?>
